### ISSUE TITLE
编辑器大小没有自适应,初始化宽高后无法随窗口改变大小

### ISSUE THREAD

**Issue by Singein** [mengdu/m-monaco-editor#2]
![screenshot_20180912_171411](https://user-images.githubusercontent.com/18239246/45415070-58ca8700-b6af-11e8-8a65-48cf99cea8bd.png)

**Comment by Singein** [comment]
需要在layoutchange里做些什么吗..

**Comment by Singein** [comment]
在下 js小白一个,最近做项目用到vue,敢问大佬,如何从你的组件中获取到官方的monaco编辑器对象呢...看了很多官方的api,但是我不知道从哪里获取monaco对象,有点蒙B...
希望大佬能耐心解答...谢谢啦

**Comment by mengdu** [comment]
可以通过 ref 在组件中拿到 `monaco` 对象，编辑器实例对象是 `editor`
如果你不想通过这个组件，可以直接用 官方的 monaco 库即可 `https://cdn.bootcss.com/monaco-editor/0.13.1/min/vs`

自适应宽度的问题，暂时还没找到api解决。

**Comment by Singein** [comment]
👌了然了

**Comment by Singein** [comment]
自适应，layout函数
