### ISSUE TITLE
Does this lib support diff editor?

### ISSUE THREAD

**Issue by Symbolk** [mengdu/m-monaco-editor#6]
I have been struggling to find a vue-monaco lib that supports diff editor well, but after trying I found that the current ones have problems more or less. So I wonder if this lib support diff editor mode?

Studied projects: 
1. https://github.com/FE-Mars/monaco-editor-vue
2. https://github.com/egoist/vue-monaco

P.S. 可中文交流

**Comment by mengdu** [comment]
这个当时忘记加了，暂时没有呢，你可以自己从 monaco 自己创建一个diff编辑器，官网有例子的。

**Comment by Symbolk** [comment]
> 这个当时忘记加了，暂时没有呢，你可以自己从 monaco 自己创建一个diff编辑器，官网有例子的。

是这个例子吧，我现在是试图在一个使用vue作为前端的electron应用中集成monaco diff，也是可以直接使用官网这种直接调用monaco API操作dom元素来进行创建吗？

**Comment by mengdu** [comment]
可以的，请查看下这个页面的代码就懂了 https://microsoft.github.io/monaco-editor/

**Comment by Symbolk** [comment]
> 可以的，请查看下这个页面的代码就懂了 https://microsoft.github.io/monaco-editor/


多谢，我暂时还是用上面第二个vue-monaco来实现了diff，虽然console会有报错，一个好像存在了很久的问题，请问你有见过吗？

https://github.com/Microsoft/monaco-editor/issues/1385
https://github.com/Microsoft/monaco-editor-webpack-plugin/issues/32
https://github.com/jaywcjlove/react-monacoeditor/issues/1

**Comment by mengdu** [comment]
没有遇到呢
